# Site settings
title: ScalaFX
email: scalafx-users@googlegroups.com
description: "ScalaFX - a simpler way of using JavaFX in Scala."
baseurl: ""
# url: "http://scalafx.org"
repository: https://github.com/scalafx/scalafx

# Build settings
markdown: kramdown
permalink: pretty
relative_permalinks: false
exclude: [vendor]

timezone: America/New_York

collections:
  docs:
    output: true
logo: img/logo-2x.png
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-avatar
